# -*- coding: utf-8 -*-
"""Ejercicios clase

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bxMwGa3gRIW04JA6Dp6BXW_N43zPqZ9d
"""

costo_consumo= float (input("Costo consumo: "))
categoria= input("Categoria: ")
num_retardos=int(input("Numero de retardos: "))
if categoria =="A":
  total= costo_consumo * 0.9
elif categoria == "B":
  total= costo_consumo * 0.8
elif categoria == "C":
   total= costo_consumo *0.7
else:
  print("No existe esa categoria")
if num_retardos<=3:
  total *= 0.9
print("El costo final es: ", total)

print("1. Area de un circulo\n2. Area rectangulo\n3. Area rectangulo")
opcion= int(input("Selecciona una opcion: "))


#opcion= int (input())

import math
def menu():
    print("1. Area de un circulo\n2. Area rectangulo\n3. Area rectangulo")
opcion= int(input("Selecciona una opcion: "))
if opcion==1:
  radio=float(input("Radio: "))
  a= math.pi * radio**2
elif opcion==2:
  base= float(input("Base: "))
  altura= float(input("Altura: "))
  a= base * altura
elif opcion==3:

  base= float(input("Base: "))
  altura= float(input("Altura: "))
  a= base * altura /2
print("El area es: ",a)

def cuentaRegresiva(n):
  while n>0:
    print(n)
    n=n-1
  print("¡Empezamos!")
cuentaRegresiva(10)

